"""Sandbox provider — a physically-based forward model of a forest scene.

WHAT THIS IS
    A simulator. It generates a synthetic forest, then renders what Sentinel-2,
    Sentinel-1 and GEDI *would* measure over it, using published forward models:

      * spectral linear mixture model  (Adams et al. 1986) for optical bands
      * Water Cloud Model              (Attema & Ulaby 1978) for SAR backscatter
      * a height/cover allometry       for aboveground biomass

WHAT THIS IS NOT
    An observation. Nothing here is satellite data, and nothing downstream is
    allowed to present it as such: every bundle it produces carries
    DataMode.SANDBOX_SIMULATION, which the API and the UI surface verbatim.

WHY IT EXISTS
    The biomass model, uncertainty propagation, confidence scoring, field
    planner and change detection are provider-agnostic. Running them against a
    forward model keeps the whole system genuinely executable and testable when
    no Earth Engine credential is present, without fabricating observations.
    When a credential is supplied, the identical downstream code runs on real
    Sentinel/GEDI pixels.
"""

from __future__ import annotations

import datetime as dt
import hashlib
from typing import Any

import numpy as np

from app.core.config import Settings, get_settings
from app.providers.base import (
    AOI,
    AuditResult,
    DataMode,
    GediSamples,
    LandcoverObservation,
    ObservationBundle,
    OpticalObservation,
    RadarObservation,
    SourceAvailability,
    SourceStatus,
    TerrainObservation,
)
from app.providers.noise import fbm, normalise, ridged
from app.science.geo import (
    analysis_grid,
    geodesic_perimeter_km,
    inside_mask,
)

# --------------------------------------------------------------------------
# Physical constants of the forward model
# --------------------------------------------------------------------------

S2_BANDS = ["B2", "B3", "B4", "B5", "B6", "B7", "B8", "B8A", "B11", "B12"]

# Endmember surface reflectances (unitless, 0-1) at Sentinel-2 band centres.
# Representative values for dense broadleaf canopy and dry bare soil.
VEG_ENDMEMBER = {
    "B2": 0.030, "B3": 0.055, "B4": 0.032, "B5": 0.085, "B6": 0.220,
    "B7": 0.290, "B8": 0.320, "B8A": 0.340, "B11": 0.160, "B12": 0.070,
}
SOIL_ENDMEMBER = {
    "B2": 0.100, "B3": 0.140, "B4": 0.190, "B5": 0.220, "B6": 0.250,
    "B7": 0.270, "B8": 0.280, "B8A": 0.290, "B11": 0.330, "B12": 0.290,
}

# Water Cloud Model parameters for C-band (Attema & Ulaby 1978 formulation).
WCM = {
    # sigma0 of a saturated canopy volume (dB), per polarisation
    "VV": {"sigma_veg_db": -6.5, "sigma_soil_db": -11.0, "B": 0.018},
    "VH": {"sigma_veg_db": -13.0, "sigma_soil_db": -21.0, "B": 0.026},
}
S1_INCIDENCE_DEG = 38.0

# Allometry: AGB (Mg/ha) from canopy height (m) and cover fraction.
AGB_A, AGB_B, AGB_C = 0.18, 2.20, 0.60

# GEDI geometry
GEDI_TRACK_SPACING_M = 600.0
GEDI_ALONG_TRACK_M = 60.0
GEDI_FOOTPRINT_M = 25.0
GEDI_LAT_LIMIT = 51.6

WORLDCOVER_TREE = 10
WORLDCOVER_SHRUB = 20
WORLDCOVER_GRASS = 30
WORLDCOVER_CROP = 40
WORLDCOVER_BARE = 60
WORLDCOVER_WATER = 80


def _seed_from(aoi_id: str, salt: str = "") -> int:
    digest = hashlib.sha256(f"{aoi_id}|{salt}".encode("utf-8")).digest()
    return int.from_bytes(digest[:7], "big")


def _db_to_linear(db: np.ndarray | float) -> np.ndarray:
    return np.power(10.0, np.asarray(db, dtype=np.float64) / 10.0)


def _linear_to_db(lin: np.ndarray) -> np.ndarray:
    return 10.0 * np.log10(np.clip(lin, 1e-9, None))


class SandboxProvider:
    """Synthetic forward model standing in for the satellite archive."""

    name = "sandbox"
    mode = DataMode.SANDBOX_SIMULATION

    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()

    # ------------------------------------------------------------------
    # Readiness / provenance
    # ------------------------------------------------------------------

    def is_ready(self) -> tuple[bool, str]:
        return True, "Sandbox forward model — synthetic scene, not an observation"

    def describe(self) -> dict[str, Any]:
        return {
            "provider": self.name,
            "mode": self.mode.value,
            "ready": True,
            "reason": "No Earth Engine credential present; running the forward model",
            "label": "Sandbox simulation",
            "warning": (
                "These figures are generated by a forward model, not measured by a "
                "satellite. They exercise the analysis pipeline; they do not describe "
                "any real forest."
            ),
            "forward_models": {
                "optical": "Spectral linear mixture model (Adams et al. 1986)",
                "radar": "Water Cloud Model (Attema & Ulaby 1978)",
                "biomass_truth": f"AGB = {AGB_A}·h^{AGB_B}·cover^{AGB_C}",
                "terrain": "Ridged multifractal + fBm",
                "gedi": (
                    f"Simulated tracks at {GEDI_TRACK_SPACING_M:.0f} m spacing, "
                    f"{GEDI_FOOTPRINT_M:.0f} m footprints"
                ),
            },
            "setup_doc": "docs/EARTH_ENGINE_SETUP.md",
            "next_step": (
                "Supply an Earth Engine service account to replace the forward model "
                "with real Sentinel-2, Sentinel-1 and GEDI observations."
            ),
        }

    # ------------------------------------------------------------------
    # Scene synthesis
    # ------------------------------------------------------------------

    def _scene(
        self, aoi: AOI, lons: np.ndarray, lats: np.ndarray, year: int
    ) -> dict[str, np.ndarray]:
        """Generate the underlying 'truth' state of the synthetic forest."""
        seed = _seed_from(aoi.aoi_id)
        lon_grid, lat_grid = np.meshgrid(lons, lats)

        # Work in a local metric frame so feature sizes are in metres, not degrees.
        lat0 = float(np.mean(lats))
        m_per_deg_lat = 111_132.0
        m_per_deg_lon = 111_320.0 * np.cos(np.radians(lat0))
        x_m = (lon_grid - lons[0]) * m_per_deg_lon
        y_m = (lats[0] - lat_grid) * m_per_deg_lat

        # --- Terrain: ridges over a broad fBm base ----------------------
        relief_scale_m = 3_500.0
        xr, yr = x_m / relief_scale_m, y_m / relief_scale_m
        base = fbm(xr * 0.7, yr * 0.7, seed, octaves=5)
        ridge = ridged(xr * 1.6, yr * 1.6, seed + 101, octaves=4)
        relief_m = 40.0 + 620.0 * normalise(0.55 * base + 0.45 * ridge)
        elevation = relief_m

        gy, gx = np.gradient(elevation)
        step_x = max(float(np.mean(np.diff(x_m[0, :]))) if x_m.shape[1] > 1 else 30.0, 1.0)
        step_y = max(float(np.mean(np.diff(y_m[:, 0]))) if y_m.shape[0] > 1 else 30.0, 1.0)
        slope = np.degrees(np.arctan(np.hypot(gx / step_x, gy / step_y)))

        # --- Hydrology proxy: distance-from-ridge drives moisture -------
        wetness = normalise(-ridge + 0.3 * fbm(xr * 2.3, yr * 2.3, seed + 211, octaves=3))

        # --- Canopy structure -------------------------------------------
        stand_scale_m = 900.0
        xs, ys = x_m / stand_scale_m, y_m / stand_scale_m
        stand = fbm(xs, ys, seed + 307, octaves=6, gain=0.55)

        # Latitude sets the biome ceiling: tropical stands carry taller canopy.
        abs_lat = abs(lat0)
        biome_ceiling_m = float(np.interp(abs_lat, [0, 15, 30, 45, 60, 75], [46, 42, 33, 30, 24, 12]))

        height = biome_ceiling_m * (
            0.22 + 0.78 * np.clip(0.75 * stand + 0.25 * wetness, 0.0, 1.0)
        )
        # Steep, high ground carries shorter canopy.
        height *= np.clip(1.0 - 0.006 * np.clip(slope - 12.0, 0.0, None), 0.45, 1.0)
        height *= np.clip(1.0 - 0.00035 * np.clip(elevation - 400.0, 0.0, None), 0.5, 1.0)

        # --- Disturbance: clearings that expand with time ---------------
        # Each synthetic site is assigned a disturbance regime from its own seed,
        # spanning effectively-protected forest to an active clearing frontier.
        # Real landscapes differ this way, and it means change detection has
        # something to find at some sites and correctly nothing at others.
        regime = ((seed >> 11) % 1000) / 1000.0
        disturbance_rate = 0.004 + 0.034 * (regime**1.6)
        years_since = max(year - 2019, 0)
        dist_field = fbm(x_m / 1_400.0, y_m / 1_400.0, seed + 977, octaves=4)
        # Threshold recedes over time -> cleared area grows year on year.
        clear_threshold = 0.88 - disturbance_rate * years_since
        cleared = dist_field > clear_threshold
        edge = (dist_field > clear_threshold - 0.05) & ~cleared

        height = np.where(cleared, height * 0.08, height)
        height = np.where(edge, height * 0.62, height)

        # --- Water bodies ------------------------------------------------
        water = (wetness > 0.94) & (slope < 2.0)
        height = np.where(water, 0.0, height)

        # --- Cover fraction from height (logistic saturation) ------------
        cover = 1.0 / (1.0 + np.exp(-(height - 7.0) / 3.4))
        cover = np.where(water, 0.0, cover)
        cover = np.clip(cover, 0.0, 0.98)

        # --- Aboveground biomass truth -----------------------------------
        agb_true = AGB_A * np.power(np.clip(height, 0.0, None), AGB_B) * np.power(
            np.clip(cover, 1e-3, None), AGB_C
        )
        agb_true = np.where(water, 0.0, agb_true)

        # --- Land cover classes -------------------------------------------
        classes = np.full(height.shape, WORLDCOVER_GRASS, dtype=np.int16)
        classes[cover > 0.35] = WORLDCOVER_TREE
        classes[(cover > 0.15) & (cover <= 0.35)] = WORLDCOVER_SHRUB
        classes[cleared & (cover <= 0.15)] = WORLDCOVER_CROP
        classes[(cover <= 0.05) & (slope > 25)] = WORLDCOVER_BARE
        classes[water] = WORLDCOVER_WATER

        return {
            "elevation": elevation,
            "slope": slope,
            "height": height,
            "cover": cover,
            "agb_true": agb_true,
            "classes": classes,
            "water": water,
            "cleared": cleared,
            "x_m": x_m,
            "y_m": y_m,
        }

    # ------------------------------------------------------------------
    # Sensor forward models
    # ------------------------------------------------------------------

    def _render_optical(
        self, scene: dict[str, np.ndarray], seed: int, year: int
    ) -> tuple[dict[str, np.ndarray], np.ndarray, float, int]:
        """Spectral linear mixture model + a synthetic cloud field."""
        rng = np.random.default_rng(seed ^ (year * 2_654_435_761))
        cover = scene["cover"]
        water = scene["water"]

        # Cloud field: large-scale fBm thresholded; sets the per-cell share of
        # clear observations rather than blanking the composite outright.
        cloud_field = fbm(scene["x_m"] / 6_000.0, scene["y_m"] / 6_000.0, seed + 1301, octaves=4)
        scene_cloud_pct = float(np.clip(6.0 + 34.0 * rng.random(), 2.0, 48.0))
        n_scenes = int(rng.integers(6, 19))
        clear_prob = np.clip(1.0 - (cloud_field - 0.45) * 1.6, 0.25, 1.0)
        valid_fraction = np.clip(
            clear_prob * (1.0 - scene_cloud_pct / 140.0), 0.12, 1.0
        )

        bands: dict[str, np.ndarray] = {}
        # Shadow fraction rises with slope — darkens all bands together.
        shade = np.clip(0.06 + 0.010 * scene["slope"], 0.0, 0.45)
        for band in S2_BANDS:
            veg = VEG_ENDMEMBER[band]
            soil = SOIL_ENDMEMBER[band]
            mixed = cover * veg + (1.0 - cover) * soil
            mixed = mixed * (1.0 - shade)
            # Water: strong absorption beyond the green edge.
            water_ref = 0.035 if band in ("B2", "B3") else 0.008
            mixed = np.where(water, water_ref, mixed)
            # Radiometric noise shrinks as more clear scenes are composited.
            sigma = 0.006 / np.sqrt(np.maximum(valid_fraction * n_scenes, 1.0))
            bands[band] = np.clip(mixed + rng.normal(0.0, 1.0, mixed.shape) * sigma, 0.0, 1.0)

        return bands, valid_fraction, scene_cloud_pct, n_scenes

    def _render_radar(
        self, scene: dict[str, np.ndarray], seed: int, year: int
    ) -> tuple[np.ndarray, np.ndarray, int]:
        """Water Cloud Model: canopy volume attenuates the soil return."""
        rng = np.random.default_rng((seed + 5501) ^ (year * 40_503))
        n_scenes = int(rng.integers(8, 26))
        cos_theta = np.cos(np.radians(S1_INCIDENCE_DEG))

        # Vegetation water content (kg/m^2) scales with AGB.
        vwc = 0.55 * np.sqrt(np.clip(scene["agb_true"], 0.0, None))
        # Soil moisture modulates the ground term.
        sm = 0.18 + 0.22 * normalise(
            fbm(scene["x_m"] / 2_500.0, scene["y_m"] / 2_500.0, seed + 733, octaves=3)
        )

        out: dict[str, np.ndarray] = {}
        for pol, p in WCM.items():
            two_way_t = np.exp(-2.0 * p["B"] * vwc / cos_theta)
            sigma_veg = _db_to_linear(p["sigma_veg_db"]) * np.clip(
                scene["cover"], 0.02, 1.0
            )
            sigma_soil = _db_to_linear(p["sigma_soil_db"]) * (0.5 + 2.0 * sm)
            total = sigma_veg * (1.0 - two_way_t) + two_way_t * sigma_soil
            # Local incidence-angle effect from terrain slope.
            total *= np.clip(1.0 + 0.012 * (scene["slope"] - 10.0), 0.5, 1.8)
            # Water: specular, near-zero backscatter.
            total = np.where(scene["water"], _db_to_linear(-22.0), total)
            # Multi-look speckle: gamma with shape = number of looks.
            looks = max(n_scenes * 4, 4)
            speckle = rng.gamma(shape=looks, scale=1.0 / looks, size=total.shape)
            out[pol] = _linear_to_db(total * speckle)

        return out["VV"], out["VH"], n_scenes

    def _simulate_gedi(
        self, aoi: AOI, scene: dict[str, np.ndarray], lons: np.ndarray, lats: np.ndarray
    ) -> GediSamples | None:
        """Sample the truth field along simulated GEDI ground tracks."""
        lat0 = float(np.mean(lats))
        if abs(lat0) > GEDI_LAT_LIMIT:
            return None

        seed = _seed_from(aoi.aoi_id, "gedi")
        rng = np.random.default_rng(seed)

        x_m, y_m = scene["x_m"], scene["y_m"]
        width_m = float(np.nanmax(x_m))
        height_m = float(np.nanmax(y_m))
        if width_m <= 0 or height_m <= 0:
            return None

        heading = np.radians(float(rng.uniform(8.0, 26.0)))  # ISS-like inclination
        ux, uy = np.sin(heading), np.cos(heading)      # along-track unit vector
        vx, vy = np.cos(heading), -np.sin(heading)     # across-track unit vector

        diag = float(np.hypot(width_m, height_m))
        offsets = np.arange(-diag, diag, GEDI_TRACK_SPACING_M) + rng.uniform(
            0, GEDI_TRACK_SPACING_M
        )
        along = np.arange(-diag, diag, GEDI_ALONG_TRACK_M)

        px, py = [], []
        for off in offsets:
            cx = width_m / 2.0 + off * vx
            cy = height_m / 2.0 + off * vy
            sx = cx + along * ux
            sy = cy + along * uy
            keep = (sx >= 0) & (sx <= width_m) & (sy >= 0) & (sy <= height_m)
            px.append(sx[keep])
            py.append(sy[keep])
        if not px:
            return None
        px = np.concatenate(px)
        py = np.concatenate(py)
        if px.size == 0:
            return None

        # Map metres back to lon/lat.
        m_per_deg_lat = 111_132.0
        m_per_deg_lon = 111_320.0 * np.cos(np.radians(lat0))
        lon = lons[0] + px / m_per_deg_lon
        lat = lats[0] - py / m_per_deg_lat

        # Nearest-cell lookup of the truth fields.
        ix = np.clip(np.searchsorted(lons, lon) - 1, 0, lons.size - 1)
        iy_desc = np.clip(np.searchsorted(-lats, -lat) - 1, 0, lats.size - 1)

        inside = inside_mask(aoi, lons, lats)[iy_desc, ix]
        if not inside.any():
            return None
        ix, iy_desc = ix[inside], iy_desc[inside]
        lon, lat = lon[inside], lat[inside]

        agb_true = scene["agb_true"][iy_desc, ix]
        h_true = scene["height"][iy_desc, ix]
        slope = scene["slope"][iy_desc, ix]
        water = scene["water"][iy_desc, ix]

        # GEDI drops shots over water, steep terrain and in daytime noise.
        keep = (~water) & (rng.random(agb_true.size) > 0.35) & (
            rng.random(agb_true.size) > np.clip(slope / 70.0, 0.0, 0.7)
        )
        if keep.sum() < 8:
            keep = (~water) & (rng.random(agb_true.size) > 0.55)
        ix, iy_desc, lon, lat = ix[keep], iy_desc[keep], lon[keep], lat[keep]
        agb_true, h_true, slope = agb_true[keep], h_true[keep], slope[keep]
        if agb_true.size == 0:
            return None

        # Published L4A relative error: roughly 25-50% at low AGB, ~20% at high.
        rel_se = np.clip(0.50 - 0.22 * np.tanh(agb_true / 120.0), 0.18, 0.55)
        agbd_se = np.clip(rel_se * agb_true, 4.0, None)
        agbd = np.clip(agb_true + rng.normal(0.0, agbd_se * 0.65), 0.0, None)
        rh98 = np.clip(h_true + rng.normal(0.0, 1.4 + 0.05 * slope), 0.0, None)

        return GediSamples(
            lon=lon,
            lat=lat,
            agbd=agbd,
            agbd_se=agbd_se,
            rh98=rh98,
            quality_flag=np.ones(agbd.size, dtype=int),
            collection="SANDBOX/GEDI_L4A_FORWARD_MODEL",
            first_date="2019-04-18",
            last_date=dt.date.today().isoformat(),
        )

    # ------------------------------------------------------------------
    # Provider interface
    # ------------------------------------------------------------------

    def audit(self, aoi: AOI, window_start: str, window_end: str) -> AuditResult:
        lons, lats, _ = analysis_grid(aoi, 1024, self.settings.grid_max_cells)
        year = int(window_end[:4])
        scene = self._scene(aoi, lons, lats, year)
        mask = inside_mask(aoi, lons, lats)

        seed = _seed_from(aoi.aoi_id)
        _, valid_fraction, cloud_pct, n_optical = self._render_optical(scene, seed, year)
        _, _, n_radar = self._render_radar(scene, seed, year)
        gedi = self._simulate_gedi(aoi, scene, lons, lats)

        inside = mask & np.isfinite(scene["cover"])
        forest_pct = (
            float(np.mean(scene["classes"][inside] == WORLDCOVER_TREE) * 100.0)
            if inside.any()
            else 0.0
        )

        n_shots = 0 if gedi is None else len(gedi)
        enough_gedi = n_shots >= self.settings.min_gedi_samples

        sources = [
            SourceAvailability(
                key="sentinel2",
                label="Sentinel-2 L2A (simulated)",
                status=SourceStatus.AVAILABLE,
                scene_count=n_optical,
                first_date=window_start,
                last_date=window_end,
                detail=f"{n_optical} simulated scenes, mean {cloud_pct:.1f}% cloud",
                metrics={
                    "mean_scene_cloud_pct": round(cloud_pct, 2),
                    "mean_clear_fraction": round(float(np.mean(valid_fraction[inside])), 3)
                    if inside.any()
                    else 0.0,
                },
            ),
            SourceAvailability(
                key="sentinel1",
                label="Sentinel-1 GRD (simulated)",
                status=SourceStatus.AVAILABLE,
                scene_count=n_radar,
                first_date=window_start,
                last_date=window_end,
                detail=f"{n_radar} simulated dual-pol acquisitions",
                metrics={"orbit_passes": ["ASCENDING", "DESCENDING"]},
            ),
            SourceAvailability(
                key="gedi",
                label="GEDI L4A biomass (simulated)",
                status=SourceStatus.AVAILABLE
                if enough_gedi
                else (SourceStatus.PARTIAL if n_shots else SourceStatus.UNAVAILABLE),
                scene_count=n_shots,
                detail=(
                    f"{n_shots} simulated footprints — "
                    + (
                        "enough to calibrate locally"
                        if enough_gedi
                        else f"below the {self.settings.min_gedi_samples}-shot minimum"
                    )
                )
                if n_shots
                else f"Outside the {GEDI_LAT_LIMIT}° GEDI latitude limit",
                metrics={"shots": n_shots, "min_required": self.settings.min_gedi_samples},
            ),
            SourceAvailability(
                key="dem",
                label="Copernicus DEM GLO-30 (simulated)",
                status=SourceStatus.AVAILABLE,
                detail=(
                    f"{np.nanmin(scene['elevation']):.0f}–"
                    f"{np.nanmax(scene['elevation']):.0f} m elevation"
                ),
                metrics={
                    "mean_slope_deg": round(float(np.nanmean(scene["slope"])), 2),
                },
            ),
            SourceAvailability(
                key="worldcover",
                label="ESA WorldCover v200 (simulated)",
                status=SourceStatus.AVAILABLE,
                detail=f"{forest_pct:.1f}% tree cover",
                metrics={"tree_cover_pct": round(forest_pct, 2)},
            ),
        ]

        if forest_pct < 5.0:
            verdict = "INSUFFICIENT_DATA"
            detail = (
                f"Only {forest_pct:.1f}% of this area is tree-covered. "
                "There is not enough forest here to audit."
            )
        elif not enough_gedi:
            verdict = "PARTIAL_DATA"
            detail = (
                f"Analysis can run, but only {n_shots} biomass reference footprints fall "
                "inside this area. The model will fall back to its regional calibration "
                "and uncertainty will be wider."
            )
        else:
            verdict = "READY"
            detail = "All primary inputs are available for this area and window."

        return AuditResult(
            aoi_id=aoi.aoi_id,
            area_km2=aoi.area_km2,
            area_ha=aoi.area_ha,
            perimeter_km=geodesic_perimeter_km(aoi.geometry),
            centroid=aoi.centroid(),
            bounds=aoi.bounds.as_list(),
            forest_cover_pct=round(forest_pct, 2),
            cloud_cover_pct=round(cloud_pct, 2),
            sources=sources,
            mode=self.mode,
            window_start=window_start,
            window_end=window_end,
            verdict=verdict,
            verdict_detail=detail,
        )

    def observe(
        self, aoi: AOI, window_start: str, window_end: str, target_cells: int
    ) -> ObservationBundle:
        lons, lats, cell_size_m = analysis_grid(
            aoi, target_cells, self.settings.grid_max_cells
        )
        mask = inside_mask(aoi, lons, lats)
        year = int(window_end[:4])
        scene = self._scene(aoi, lons, lats, year)
        seed = _seed_from(aoi.aoi_id)

        bands, valid_fraction, cloud_pct, n_optical = self._render_optical(scene, seed, year)
        vv, vh, n_radar = self._render_radar(scene, seed, year)
        gedi = self._simulate_gedi(aoi, scene, lons, lats)

        bundle = ObservationBundle(
            aoi=aoi,
            lons=lons,
            lats=lats,
            mask=mask,
            cell_size_m=cell_size_m,
            window_start=window_start,
            window_end=window_end,
            mode=self.mode,
            optical=OpticalObservation(
                bands=bands,
                scene_count=n_optical,
                cloud_cover_pct=cloud_pct,
                valid_fraction=valid_fraction,
                first_date=window_start,
                last_date=window_end,
                collection="SANDBOX/S2_FORWARD_MODEL",
                resolution_m=10,
            ),
            radar=RadarObservation(
                vv_db=vv,
                vh_db=vh,
                scene_count=n_radar,
                first_date=window_start,
                last_date=window_end,
                collection="SANDBOX/S1_FORWARD_MODEL",
                orbit="ASCENDING/DESCENDING",
                resolution_m=10,
            ),
            gedi=gedi,
            terrain=TerrainObservation(
                elevation_m=scene["elevation"],
                slope_deg=scene["slope"],
                collection="SANDBOX/DEM_FORWARD_MODEL",
                resolution_m=30,
            ),
            landcover=LandcoverObservation(
                classes=scene["classes"].astype(np.float64),
                tree_mask=scene["classes"] == WORLDCOVER_TREE,
                collection="SANDBOX/WORLDCOVER_FORWARD_MODEL",
                year=year,
                resolution_m=10,
            ),
        )
        return bundle
